spring: 
  profiles: 
    active: 
      -dev
     
---
spring: 
  profiles: dev
  application: 
   name: microservicecloud-config-bokesoft-dev
  
---
spring: 
  profiles: test
  application: 
   name: microservicecloud-config-bokesoft-test
 

